// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace XMLToHelperClass
{
    internal sealed partial class Vsix
    {
        public const string Id = "XMLToHelperClass.6dc52291-66dd-4a2f-a1c7-9d16781c8694";
        public const string Name = "XML To Helper Class Converter";
        public const string Description = @"Used to convert XML file into Helper Class";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Adnan Džindo";
        public const string Tags = "";
    }
}
